Repository Elao/elao_, pull requests merged in 2021-05, with the labels that each got.

#311 Signature image URL
  templates/team/mail_signature.html.twig
Labels: review 🔍

#305 [Blog] Add a Github edit link to articles
  .env
  .github/workflows/build_pr.yaml
  assets/scss/components/_brick-contribute.scss
  assets/scss/style.scss
  config/routes.yaml
  config/routes/external/github.yaml
  config/services.yaml
  src/Model/Article.php
  src/Router/ExternalUrlGenerator.php
  src/Stenope/Processor/GithubEditLinkProcessor.php
  src/Twig/Extension/ExternalUrlExtension.php
  templates/blog/article.html.twig
Labels: review 🔍

#314 [SEO] Force meta robots "noindex" on staging
  .env
  .github/workflows/build_pr.yaml
  .github/workflows/build_static.yaml
  config/packages/framework.yaml
  config/packages/twig.yaml
  templates/base.html.twig
Labels: review 🔍

#320 [Github] Attempt to auto-clean a PR deployment on merge/close
  .github/workflows/clean_pr_preview.yaml
Labels: enhancement, review 🔍

#321 Add .well-known/security.txt
  config/packages/stenope.yaml
  public/.well-known/security.txt
Labels: review 🔍

#296 Musique Music case study
  content/case-study/musique-music.md
  public/images/casestudies/headers/musique-music-banner.jpg
  public/images/casestudies/musique-music-homepage.jpg
  public/images/casestudies/musique-music-playlists.jpg
  public/images/casestudies/musique-music-results.jpg
Labels: review 🔍

#329 Link accessibility
  assets/scss/pages/_page-values.scss
  content/technologies/accessibilite.md
  templates/site/values.html.twig
  templates/technology/technology.html.twig
Labels: review 🔍

#327 [Blog] Link authors
  assets/scss/components/_article-author.scss
  content/blog/styleguide/example.md
  templates/blog/article.html.twig
  templates/blog/index.html.twig
Labels: review 🔍

#332 [Blog] Rebranding tech: lien accessibilité
  content/blog/elao/rebranding-la-tech.md
Labels: review 🔍

#333 [Blog] - Rebranding - Seconde lecture
  content/blog/elao/rebranding-l-avenir.md
Labels: review 🔍

#287 Fix 404
  content/blog/dev/comment-demarrer-tdd-en-php.md
  content/blog/dev/design-pattern-abstract-factory.md
  content/blog/dev/design-pattern-decorator.md
  content/blog/dev/ecrire-des-tests-behat-proches-de-son-domaine.md
  content/blog/dev/no-index-staging-symfony.md
  content/blog/dev/pourquoi-devriez-vous-utiliser-vue-js-dans-vos-projets.md
  content/blog/dev/progressive-web-app-chalkboard-education-elearning-sans-internet.md
  content/blog/dev/realisez-une-application-vue-js-avec-vue-cli.md
  content/blog/dev/retour-experience-matomo.md
  content/blog/styleguide/example.md
  content/job/job-developpeur-backend-lyon-2019.md
  content/technologies/elasticsearch.md
  content/technologies/symfony.md
Labels: content 📝

#334 Blogpost retour sur le seminaire
  assets/scss/generic/_img.scss
  content/blog/elao/teambuilding-a-distance.md
  public/images/posts/2021/teambuilding/ananas.gif
  public/images/posts/2021/teambuilding/ananas.jpeg
  public/images/posts/2021/teambuilding/ananas.mp4
  public/images/posts/2021/teambuilding/ananas.webm
  public/images/posts/2021/teambuilding/canard-banane.gif
  public/images/posts/2021/teambuilding/canard-banane.jpeg
  public/images/posts/2021/teambuilding/canard-banane.mp4
  public/images/posts/2021/teambuilding/canard-banane.webm
  public/images/posts/2021/teambuilding/chataigne.gif
  public/images/posts/2021/teambuilding/chataigne.jpeg
  public/images/posts/2021/teambuilding/chataigne.mp4
  public/images/posts/2021/teambuilding/chataigne.webm
  public/images/posts/2021/teambuilding/cochon.gif
  public/images/posts/2021/teambuilding/cochon.jpeg
  public/images/posts/2021/teambuilding/cochon.mp4
  public/images/posts/2021/teambuilding/cochon.webm
  public/images/posts/2021/teambuilding/dodo.gif
  public/images/posts/2021/teambuilding/form-sujets.png
  public/images/posts/2021/teambuilding/hbdi-entrepreneur.png
  public/images/posts/2021/teambuilding/hbdi-ingenieur.png
  public/images/posts/2021/teambuilding/hbdi.png
  public/images/posts/2021/teambuilding/jitsi.png
  public/images/posts/2021/teambuilding/monmoi.png
  public/images/posts/2021/teambuilding/savethedate.png
  public/images/posts/2021/teambuilding/solution1.jpg
  public/images/posts/2021/teambuilding/solution2.jpg
  public/images/posts/2021/teambuilding/solution3.jpg
  public/images/posts/2021/teambuilding/solution4.jpg
  public/images/posts/2021/teambuilding/solution5.jpg
  public/images/posts/2021/teambuilding/workadventure.png
  src/Stenope/Processor/AssetsProcessor.php
Labels: review 🔍

#341 Fix brick contribute
  assets/scss/style.scss
Labels: review 🔍

#319 [Blog] Fix bricks margins
  assets/scss/components/_article-footer.scss
Labels: review 🔍

#340 Rex MiXiT côté orga
  content/blog/elao/rex-orga-mixit-2021.md
  public/images/posts/2021/mixit/conference-sinatou.png
  public/images/posts/2021/mixit/conference_esther.jpg
  public/images/posts/2021/mixit/crazy.gif
  public/images/posts/2021/mixit/mixit-2021.png
  public/images/posts/2021/mixit/mixit-freeze.png
  public/images/posts/2021/mixit/mixit-fun.png
  public/images/posts/2021/mixit/mixit-manufacture-tabacs.png
  public/images/posts/2021/mixit/quizz-mixit.jpg
  public/images/posts/2021/mixit/quizz-mixit2.jpg
  public/images/posts/2021/mixit/wa-mixit.png
Labels: content 📝

#344 Update nice to have
  content/job/job-frontend-alternant-integration.md
Labels: review 🔍
