Repository Elao/elao_, pull requests merged in 2021-07, with the labels that each got.

#372 Fix éléments non-interactifs si le JS est désactivé
  assets/scss/style.scss
Labels: bug 🕷, review 🔍

#373 Passage de l'offre d'alternance en inactive
  content/job/legacy/job-frontend-alternant-integration.md
Labels: review 🔍

#368 [blog] php8 attributes in symfony
  content/blog/dev/les-attributs-php-8-dans-symfony.md
  public/images/posts/2021/php-attributes-symfony/symfony-attributes-doc.png
  public/images/posts/thumbnails/les-attributs-php-8-dans-symfony.jpg
Labels: blog, content 📝

#378 [CI] Auto deploy on master push / merge PR to master
  .github/workflows/deploy.yaml
Labels: review 🔍

#381 elaomojis processor
  assets/scss/components/_elaomojis.scss
  config/services.yaml
  package-lock.json
  src/Emoji/ElaomojiParser.php
  src/Stenope/Processor/ElaomojisProcessor.php
Labels: dev

#385 [Blog] Fix date de dernière modification
  content/blog/dev/les-attributs-php-8-dans-symfony.md
  content/blog/elao/anne-laure-developpeuse-web-chez-elao-depuis-3-ans.md
  content/blog/elao/trame-itw.md
  src/Command/GenerateArticleCommand.php
Labels: review 🔍

#382 [Blog] Permettre la publication auto d'articles programmés
  .env
  .github/workflows/deploy.yaml
  assets/scss/base/_variables.scss
  assets/scss/components/_alert.scss
  composer.json
  composer.lock
  config/services.yaml
  src/Command/GenerateArticleCommand.php
  src/Controller/BlogController.php
  src/Controller/CaseStudyController.php
  src/Controller/JobController.php
  src/Controller/SiteController.php
  src/Controller/TeamController.php
  src/Controller/TechnologyController.php
  src/Legacy/HtaccessGenerator.php
  src/Model/Article.php
  src/Stenope/Listener/BuildListener.php
  src/Stenope/Manager/FilteringArticlesContentManager.php
  templates/blog/article.html.twig
Labels: blog, review 🔍

#386 Elaomojis link in footer
  templates/footer.html.twig
Labels: review 🔍

#387 Xav R and Yves emojis
  content/misc/elaomojis.yaml
Labels: review 🔍

#389 [Debug] CLI Suggested queries
  composer.json
  composer.lock
  config/services.yaml
  src/Model/Article.php
  src/Model/Member.php
  src/Stenope/ExpressionLanguage/ExpressionLanguageProvider.php
Labels: review 🔍
