Repository Elao/elao_, pull requests merged in 2021-08, with the labels that each got.

#393 Go node 16 for npm 7
  .github/workflows/deploy.yaml
  .github/workflows/deploy_pr_preview.yaml
  .github/workflows/deploy_staging.yaml
  .github/workflows/tests.yaml
  .manala.yaml
  .manala/Dockerfile
  .manala/README.md
  .manala/docker-compose.yaml
  .manala/templates/profile.d/message.sh
  .npmrc
  .nvmrc
  README.md
  package-lock.json
  package.json
Labels: review 🔍

#376 [blog] interview maxime
  content/blog/elao/maxime-developpeur-web-depuis-10-ans.md
  public/images/posts/2021/interview/fast-travel.jpg
  public/images/posts/2021/interview/max-colin-photo.jpg
  public/images/posts/2021/itw-max.jpeg
Labels: blog

#397 new profile on tribe
  content/member/ayarkina.yaml
  content/member/sludovicdelys.yaml
Labels: review 🔍, intégration 📐🔨
