Repository Elao/elao_, pull requests merged in 2021-12, with the labels that each got.

#432 Delete old route config
  composer.json
  composer.lock
  config/routes/accesseo.yaml
Labels: bug 🕷

#433 Glossaire : page sur la double authentification
  content/term/authentification-double-facteurs-2FA.md
Labels: content 📝

#442 fixed layout glossary
  templates/glossary/term.html.twig
Labels: bug 🕷, intégration 📐🔨
