Repository Elao/elao_, pull requests merged in 2021-09, with the labels that each got.

#399 Fix footer alignement
  assets/scss/components/_footer.scss
Labels: review 🔍

#404 Nuit du hack XV fix content
  content/blog/elao/nuit-du-hack-XV.md
  templates/blog/article.html.twig
Labels: review 🔍

#407 Article facilitation
  content/blog/methodo/gestion-de-projet-sans-chef-de-projet.md
  public/images/posts/headers/whiteboard-product-roadmap.jpg
Labels: blog

#414 Fixed width
  assets/scss/components/_article-info.scss
Labels: intégration 📐🔨

#409 ITW Sabrina ✨
  content/blog/elao/sabrina-alternante-en-integration.md
  public/images/posts/2021/interview/sab-ludo-dessin.jpg
  public/images/posts/thumbnails/sabrina-ludo-samoens.jpg
Labels: blog

#418 Integrated gifs
  content/blog/elao/sabrina-alternante-en-integration.md
  public/images/posts/2021/itw-sabrina/bugs-bunny-coffee.gif
  public/images/posts/2021/itw-sabrina/hello-sailor-moon.gif
  public/images/posts/2021/itw-sabrina/secret-the-office.gif
  public/images/posts/2021/itw-sabrina/working-star-wars.gif
Labels: intégration 📐🔨

#420 Update matomo domain
  templates/base.html.twig
Labels: review 🔍
