Repository Elao/elao_, pull requests merged in 2021-06, with the labels that each got.

#345 Better banners
  assets/scss/components/_banner-case-study.scss
  assets/scss/components/_banner-home.scss
  assets/scss/components/_banner-methodology.scss
  assets/scss/components/_banner-services.scss
  assets/scss/components/_banner-team.scss
  assets/scss/components/_banner-values.scss
  assets/scss/components/_banner.scss
  assets/scss/components/_breadcrumb.scss
  assets/scss/components/_contact.scss
  assets/scss/components/_header.scss
  assets/scss/components/_nav-mobile.scss
  assets/scss/components/_titles.scss
  assets/scss/pages/_page-contact.scss
  assets/scss/pages/_page-services.scss
  templates/site/contact.html.twig
  templates/site/home.html.twig
  templates/site/methodology.html.twig
  templates/site/services.html.twig
Labels: review 🔍

#347 Fix job offer(s) pluralization + move footer in dedicated template
  templates/base.html.twig
  templates/footer.html.twig
  templates/site/home.html.twig
  translations/messages+intl-icu.fr.yaml
Labels: review 🔍

#338 Better buttons
  assets/scss/components/_btn.scss
  templates/blog/index.html.twig
  templates/case_study/index.html.twig
  templates/case_study/show.html.twig
  templates/job/index.html.twig
  templates/partials/svg-arrow.html.twig
  templates/site/contact.html.twig
  templates/site/home.html.twig
  templates/site/services.html.twig
  templates/site/values.html.twig
  templates/team/index.html.twig
Labels: review 🔍

#353 [Deps] Update recipes & deps
  .gitignore
  .php-cs-fixer.dist.php
  Makefile
  bin/console
  bin/phpunit
  composer.json
  composer.lock
  config/bundles.php
  config/packages/framework.yaml
  config/packages/prod/deprecations.yaml
  config/packages/prod/monolog.yaml
  config/packages/prod/routing.yaml
  config/packages/routing.yaml
  config/packages/translation.yaml
  config/preload.php
  config/routes/accesseo.yaml
  config/routes/dev/accesseo.yaml
  config/routes/dev/framework.yaml
  config/routes/framework.yaml
  config/services.yaml
  phpunit.xml.dist
  public/index.php
  src/Kernel.php
  src/Stenope/Processor/CategoryProcessor.php
  symfony.lock
Labels: review 🔍

#351 Webpack HMR
  .manala/docker-compose.yaml
  Makefile
  README.md
  assets/js/app.js
  package-lock.json
  package.json
  templates/base.html.twig
  webpack.config.js
Labels: review 🔍

#355 Delete chatfocus.jpg
  public/images/posts/headers/chatfocus.jpg
Labels: bug 🕷, review 🔍

#357 [Manala] Update
  .manala.yaml
  .manala/Dockerfile
  .manala/Makefile
  .manala/README.md
  .manala/docker-compose.darwin.yaml
  .manala/docker-compose.linux.yaml
  .manala/docker-compose.windows.yaml
  .manala/docker-compose.yaml
  .manala/docker/bin/entrypoint.sh
  .manala/docker/entrypoint
  .manala/docker/etc/ssh_config
  .manala/docker/make.mk
  .manala/make/help.mk
  .manala/make/math.mk
  .manala/make/text.mk
  .manala/mariadb/app.sql
  .manala/nginx/app.conf
  .manala/php/fpm.conf
  .manala/php/xdebug/darwin.ini
  .manala/php/xdebug/linux.ini
  .manala/php/xdebug/windows.ini
  .manala/templates/nginx/project.conf
  .manala/templates/php/default/cli/conf.d/project.ini
  .manala/templates/php/default/cli/conf.d/xdebug.ini
  .manala/templates/php/default/fpm/conf.d/project.ini
  .manala/templates/php/default/fpm/conf.d/xdebug.ini
  .manala/templates/php/default/fpm/project.conf
  .manala/templates/profile.d/message.sh
  .manala/templates/services/.s6-svscan/finish
  .manala/templates/services/nginx/down-signal
  .manala/templates/services/nginx/run
  .manala/templates/services/php/down-signal
  .manala/templates/services/php/run
  .manala/templates/ssh/ssh_config
  .manala/templates/starship/config.toml
  Makefile
  README.md
Labels: dev, review 🔍

#356 Blog : Afup Day 2 2021
  content/blog/elao/afup-day-2-2021.md
  public/images/posts/2021/afup-day-2021/afup-day-2021-2.png
Labels: content 📝, review 🔍

#256 PHP 8
  .github/workflows/build_pr.yaml
  .github/workflows/build_static.yaml
  .github/workflows/deploy.yaml
  .github/workflows/tests.yaml
  .manala.yaml
  .manala/Dockerfile
  .manala/docker-compose.yaml
  .manala/templates/profile.d/message.sh
  .php-version
  Makefile
  README.md
  composer.json
  composer.lock
  src/Command/GenerateArticleCommand.php
  src/Controller/BlogController.php
  src/Controller/CaseStudyController.php
  src/Controller/LegacyController.php
  src/Controller/SiteController.php
Labels: dev, review 🔍

#359 [Blog] Rework last modified on articles
  content/blog/dev/donnees-structurees-offre-emploi.md
  content/blog/styleguide/example.md
  src/Model/Article.php
  templates/blog/article.html.twig
Labels: review 🔍
