Repository Elao/elao_, pull requests merged in 2022-09, with the labels that each got.

#475 Add swup
  assets/controllers.json
  assets/js/app.js
  assets/js/controllers/swup_matomo_controller.js
  assets/js/controllers/swup_scroll_controller.js
  assets/js/controllers/toggle_controller.js
  composer.json
  composer.lock
  config/packages/twig.yaml
  package-lock.json
  package.json
  symfony.lock
  templates/base.html.twig
  templates/macros.html.twig
  templates/partials/footer.html.twig
Labels: review 🔍

#440 Article de blog conférence Accesseo
  .editorconfig
  content/blog/elao/.ztr-directory
  content/blog/elao/conference-accesseo-2021.md
  content/term/accesseo.md
  public/images/accesseo/accesseo-accessbility-profiler.png
  public/images/accesseo/accesseo-accessessibility.png
  public/images/accesseo/accesseo-seo-insights.png
  public/images/accesseo/accesseo-seo-microdata.png
  public/images/accesseo/accesseo-seo.png
Labels: blog

#478 Add Quentin as team member
  content/member/qbrouillet.yaml
Labels: review 🔍

#479 Add Camille to tribu
  content/member/ccastillo.yaml
Labels: review 🔍

#485 [Global] - Uniformize social network media tags
  templates/base.html.twig
  templates/blog/article.html.twig
  templates/case_study/index.html.twig
  templates/case_study/show.html.twig
  templates/site/contact.html.twig
  templates/site/elaomojis.html.twig
  templates/site/home.html.twig
  templates/site/methodology.html.twig
  templates/site/services.html.twig
  templates/site/values.html.twig
  templates/team/index.html.twig
Labels: review 🔍

#488 [Global] - Update legal notice
  config/packages/twig.yaml
  templates/site/legal.html.twig
Labels: review 🔍

#484 [Members] Add Océane
  content/images/members/ogandillon.jpg
  content/member/ogandillon.yaml
Labels: wip 🛠

#487 [SEO] - Add structured data to blog post
  templates/base.html.twig
  templates/blog/article.html.twig
Labels: review 🔍
