Repository Elao/elao_, pull requests merged in 2024-10, with the labels that each got.

#602 [Blog] Pratique du DDD
  content/blog/dev/architecture-hexagonale-symfony.md
  content/blog/dev/ddd-practice.md
  content/images/blog/2024/ddd-bg.jpg
  content/images/blog/2024/ddd-bible.jpg
  content/images/blog/2024/ddd-escher.jpg
  content/images/blog/2024/ddd-layers.jpg
Labels: review 🔍

#635 [Blog] Pratique du DDD - some minor updates
  content/blog/dev/ddd-practice.md
Labels: review 🔍

#636 [Lazy] - Upgrade lazy stack to PHP8.3
  .manala.yaml
  .manala/Makefile
  .manala/README.md
  .manala/docker/Dockerfile
  .manala/docker/compose.yaml
  .manala/docker/compose/docker.bridge.yaml
  .manala/docker/compose/docker.yaml
  .manala/docker/compose/env.file.yaml
  .manala/docker/compose/project.cache.yaml
  .manala/docker/compose/ssh-agent.yaml
  .manala/docker/compose/ssh.agent-bridge.yaml
  .manala/docker/compose/term.yaml
  .manala/docker/docker.mk
  .manala/docker/entrypoint.sh
  .manala/docker/services/maildev/compose.yaml
  .manala/docker/services/mariadb/compose.yaml
  .manala/docker/services/phpmyadmin/compose.yaml
  .manala/etc/direnv/config.toml
  .manala/etc/gitconfig
  .manala/etc/profile.d/message.sh
  .manala/etc/profile.d/oh-my-bash.sh
  .manala/etc/profile.d/zz-direnv.sh
  .manala/github/system/run/action.yaml
  .manala/github/system/setup/action.yaml
  .manala/gitlab/system.yaml
Labels: review 🔍

#638 [BLOG] Itw Emmanuelle
  content/blog/elao/emmanuelle-alternante-direction-artistique.md
  content/images/blog/2024/itw-emmanuelle/banner.jpg
  content/images/blog/2024/itw-emmanuelle/confused-math.gif
Labels: blog

#642 [member] ciao Arti
  content/member/afarrugia.yaml
Labels: content 📝, review 🔍
